---
kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/shivakar/csv

steps:
- name: test
  image: golang:latest
  commands:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

---
kind: pipeline
name: alpine

workspace:
  base: /go
  path: src/github.com/shivakar/csv

steps:
- name: test
  image: golang:alpine
  commands:
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...